name: worldGuanPlugin
main: main.WorldGuanMain
version: 1.0
api-version: 1.16
commands:
  worldguan:
    description: 설정을 조작합니다. monster/player true/false를 붙여 설정하십시오
    usage: /<command> [monster/player] [true/false]
    permission: op